server:
  port: 18080
spring:
  application:
    name: dreamdate-app-server
  redis:
    password: wLfBobe!C_4o4azXKY84.MEwjtX
    host: 42.193.219.12
    port: 6379
    database: 0
  cloud: #nacos配置
    nacos:
      discovery:
        server-addr: 139.9.76.182:8848
dreamdate:
  sms:
    signName: DreamDate
    region_id: cn-hangzhou
    template_code: SMS_11759122239
    access_key_id: FAKE_OH_PLEASE_REPLACE_IT_WITH_YOUR_OWN
    access_key_secret: FAKE_OH_PLEASE_REPLACE_IT_WITH_YOUR_OWN
  alibaba:
    recognize:
      face:
        access_key_id: FAKE_OH_PLEASE_REPLACE_IT_WITH_YOUR_OWN
        access_key_secret: FAKE_OH_PLEASE_REPLACE_IT_WITH_YOUR_OWN

dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
#  cloud:
#    subscribed-services: dreamdate-dubbo-db

fdfs:
  so-timeout: 3000
  connect-timeout: 600
  thumb-image:
    height: 200
    width: 200
  tracker-list: 139.9.76.182:22122
  web-server-url: http://139.9.76.182:8888/

logging:
  level:
    cn.kilo.dreamdate_app_server.controller: debug